#!/usr/bin/env python3
"""
make_tables.py -- generate dictforge paper LaTeX tables from benchmark CSVs.

Reads results/benchmark_v2.csv (schema: experiment,corpus,level,variant,
dict_size,ratio,train_wall_s,note) and, if present, results/parity_v2.csv
(same schema assumed; degrades gracefully if the file is absent or only
partially populated -- the parity campaign, tools/run_parity.py, may still
be running). Emits paper/latex/tables/*.tex:

  t1_main.tex         -- MAIN experiment: per corpus x level, nodict /
                          default / tuned / full / rawconcat ratios, plus
                          the "full vs default" ratio delta (%).
  t2_equalcompute.tex -- E1 equal-compute sweep: winner ratio vs default
                          vs full (ours), plus "ours vs equal-compute"
                          delta (%).
  t3_baselines.tex    -- E2 klauspost/compress baseline: requested vs
                          emitted dict size (flagging klauspost's
                          undersized-emission behaviour, dict_size <<
                          requested), klauspost ratio vs default vs ours.
  t4_parity.tex        -- matched-size / production-config comparisons
                          from results/parity_v2.csv. Emits a \todo
                          placeholder if that file is absent; degrades to
                          whatever rows/columns are present if it is only
                          partially populated.

Every generated file opens with a header comment declaring it is
auto-generated by this script (do not hand-edit). All numbers come from
the CSV(s); nothing is hardcoded. Ratios are formatted to 3 decimal
places; deltas are signed percentages to 2 decimal places. This script
must never crash on a partial/missing CSV: missing inputs degrade to a
placeholder table or a reduced set of columns/rows, with a warning
printed to stderr.

Usage:
    python3 tools/make_tables.py [--csv results/benchmark_v2.csv]
                                  [--parity-csv results/parity_v2.csv]
                                  [--out-dir paper/latex/tables]
"""
import argparse
import csv
import re
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
DEFAULT_CSV = REPO_ROOT / "results" / "benchmark_v2.csv"
DEFAULT_PARITY_CSV = REPO_ROOT / "results" / "parity_v2.csv"
DEFAULT_OUT_DIR = REPO_ROOT / "paper" / "latex" / "tables"

DEFAULT_DICT_BYTES = 112640  # 110KB, the zstd CLI / RocksDB / ScyllaDB default

_TRAILING_SIZE_RE = re.compile(r"_(\d+)$")
_SIZE_SOURCE_RE = re.compile(r"size_source=([\w.]+)")

GENERATOR_NOTE = "tools/make_tables.py"


def warn(msg):
    print(f"[make_tables] WARNING: {msg}", file=sys.stderr)


def info(msg):
    print(f"[make_tables] {msg}")


# ---------------------------------------------------------------------
# data loading
# ---------------------------------------------------------------------

def load_rows(csv_path):
    """Tolerant CSV loader matching the benchmark_v2.csv schema. Returns
    [] (with a warning) if the file is absent; skips and warns on any
    individual malformed row rather than aborting."""
    if not csv_path.exists():
        warn(f"{csv_path} not found; skipping")
        return []
    rows = []
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for raw in reader:
            try:
                rows.append({
                    "experiment": raw["experiment"],
                    "corpus": raw["corpus"],
                    "level": int(raw["level"]),
                    "variant": raw["variant"],
                    "dict_size": int(raw["dict_size"]),
                    "ratio": float(raw["ratio"]),
                    "train_wall_s": float(raw["train_wall_s"]) if raw.get("train_wall_s") else 0.0,
                    "note": raw.get("note") or "",
                })
            except (KeyError, ValueError) as e:
                warn(f"skipping malformed row {raw!r}: {e}")
    return rows


def corpora_levels(rows):
    """Sorted (corpus, level) pairs present in rows."""
    pairs = sorted({(r["corpus"], r["level"]) for r in rows})
    return pairs


def variant_requested_size(variant):
    m = _TRAILING_SIZE_RE.search(variant)
    return int(m.group(1)) if m else None


def size_source(note):
    m = _SIZE_SOURCE_RE.search(note)
    return m.group(1) if m else None


# ---------------------------------------------------------------------
# formatting helpers
# ---------------------------------------------------------------------

def esc(s):
    """Escape LaTeX special characters in free text (corpus names,
    notes)."""
    s = str(s)
    return (
        s.replace("\\", r"\textbackslash{}")
         .replace("_", r"\_")
         .replace("%", r"\%")
         .replace("&", r"\&")
         .replace("#", r"\#")
    )


def fmt_ratio(x):
    if x is None:
        return "--"
    return f"{x:.3f}"


def fmt_delta_pct(x):
    if x is None:
        return "--"
    return f"{x:+.2f}\\%"


def fmt_bytes(n):
    if n is None:
        return "--"
    return f"{n:,}"


def delta_pct(new, base):
    if base is None or base == 0 or new is None:
        return None
    return (new - base) / base * 100.0


def header_comment(script_line):
    return (
        "% AUTO-GENERATED FILE -- DO NOT HAND-EDIT.\n"
        f"% Generated by {GENERATOR_NOTE} ({script_line}).\n"
        "% Regenerate with: python3 tools/make_tables.py\n"
    )


# ---------------------------------------------------------------------
# t1_main.tex
# ---------------------------------------------------------------------

def build_t1_main(rows, out_dir):
    main_rows = [r for r in rows if r["experiment"] == "MAIN"]
    if not main_rows:
        warn("no MAIN rows found; t1_main.tex will be a placeholder")
        write_placeholder(
            out_dir / "t1_main.tex",
            "t1: no MAIN experiment rows found in the benchmark CSV.",
            "t1_main",
        )
        return

    by_cl = defaultdict(dict)
    for r in main_rows:
        by_cl[(r["corpus"], r["level"])][r["variant"]] = r["ratio"]

    lines = []
    lines.append(header_comment("t1_main: MAIN experiment, per corpus x level"))
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\caption{Compression ratio (heldout, batch compression) by corpus and level "
                 r"across dictionary variants: no dictionary, \texttt{zstd --train} default "
                 r"(110KB), our trainer's stage-1-only \emph{tuned} variant, our trainer's "
                 r"full pipeline, and a random raw-concatenation control. "
                 r"$\Delta$ is the ratio gain of \emph{full} over \emph{default}.}")
    lines.append(r"\label{tab:t1-main}")
    lines.append(r"\resizebox{\linewidth}{!}{%")
    lines.append(r"\begin{tabular}{llrrrrrr}")
    lines.append(r"\toprule")
    lines.append(r"Corpus & Level & No-dict & Default & Tuned & Full (ours) & Raw-concat & "
                 r"$\Delta$ Full vs.\ Default \\")
    lines.append(r"\midrule")
    for corpus, level in corpora_levels(main_rows):
        v = by_cl[(corpus, level)]
        default = v.get("default")
        full = v.get("full")
        d = delta_pct(full, default)
        lines.append(
            f"{esc(corpus)} & {level} & {fmt_ratio(v.get('nodict'))} & {fmt_ratio(default)} & "
            f"{fmt_ratio(v.get('tuned'))} & {fmt_ratio(full)} & {fmt_ratio(v.get('rawconcat'))} & "
            f"{fmt_delta_pct(d)} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}%")
    lines.append(r"}")
    lines.append(r"\end{table}")
    write_lines(out_dir / "t1_main.tex", lines)


# ---------------------------------------------------------------------
# t2_equalcompute.tex
# ---------------------------------------------------------------------

def build_t2_equalcompute(rows, out_dir):
    main_rows = [r for r in rows if r["experiment"] == "MAIN"]
    e1_rows = [r for r in rows if r["experiment"] == "E1"]
    if not e1_rows:
        warn("no E1 rows found; t2_equalcompute.tex will be a placeholder")
        write_placeholder(
            out_dir / "t2_equalcompute.tex",
            "t2: no E1 (equal-compute) experiment rows found in the benchmark CSV.",
            "t2_equalcompute",
        )
        return

    main_by_cl = defaultdict(dict)
    for r in main_rows:
        main_by_cl[(r["corpus"], r["level"])][r["variant"]] = r["ratio"]

    winners = {}
    for r in e1_rows:
        if r["variant"] == "winner":
            winners[(r["corpus"], r["level"])] = r["ratio"]

    pairs = sorted(set(main_by_cl) | set(winners))
    lines = []
    lines.append(header_comment("t2_equalcompute: E1 equal-compute sweep vs default vs full"))
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\caption{Equal-compute control (E1): a stock \texttt{cover} size sweep is "
                 r"run under the same wall-clock budget our full pipeline used, and the "
                 r"best validation-set candidate (\emph{winner}, no refit-on-full) is reported "
                 r"on heldout. $\Delta$ is our full pipeline's ratio gain over the equal-compute "
                 r"winner.}")
    lines.append(r"\label{tab:t2-equalcompute}")
    lines.append(r"\resizebox{\linewidth}{!}{%")
    lines.append(r"\begin{tabular}{llrrrr}")
    lines.append(r"\toprule")
    lines.append(r"Corpus & Level & Default & Equal-compute winner (E1) & Full (ours) & "
                 r"$\Delta$ Ours vs.\ Equal-compute \\")
    lines.append(r"\midrule")
    for corpus, level in pairs:
        default = main_by_cl.get((corpus, level), {}).get("default")
        full = main_by_cl.get((corpus, level), {}).get("full")
        winner = winners.get((corpus, level))
        d = delta_pct(full, winner)
        lines.append(
            f"{esc(corpus)} & {level} & {fmt_ratio(default)} & {fmt_ratio(winner)} & "
            f"{fmt_ratio(full)} & {fmt_delta_pct(d)} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}%")
    lines.append(r"}")
    lines.append(r"\end{table}")
    write_lines(out_dir / "t2_equalcompute.tex", lines)


# ---------------------------------------------------------------------
# t3_baselines.tex
# ---------------------------------------------------------------------

def build_t3_baselines(rows, out_dir):
    main_rows = [r for r in rows if r["experiment"] == "MAIN"]
    e2_rows = [r for r in rows if r["experiment"] == "E2"]
    if not e2_rows:
        warn("no E2 rows found; t3_baselines.tex will be a placeholder")
        write_placeholder(
            out_dir / "t3_baselines.tex",
            "t3: no E2 (klauspost/compress baseline) experiment rows found in the benchmark CSV.",
            "t3_baselines",
        )
        return

    main_by_cl = defaultdict(dict)
    for r in main_rows:
        main_by_cl[(r["corpus"], r["level"])][r["variant"]] = r["ratio"]

    UNDERSIZED_FRAC = 0.5  # emitted < half the requested size counts as "undersized"
    any_undersized = False

    lines = []
    lines.append(header_comment("t3_baselines: E2 klauspost/compress vs default vs ours"))
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\caption{klauspost/compress \texttt{builddict} baseline (E2), evaluated with "
                 r"our zstd on heldout, against the stock \texttt{zstd --train} default and our "
                 r"full pipeline. Requested is the \texttt{-maxdict}-equivalent budget passed to "
                 r"\texttt{builddict}; Emitted is the actual dictionary size produced. "
                 r"$\dagger$ marks rows where klauspost emitted less than half its requested "
                 r"budget, the undersized-emission behaviour discussed in "
                 r"Section~\ref{sec:related-work}.}")
    lines.append(r"\label{tab:t3-baselines}")
    lines.append(r"\resizebox{\linewidth}{!}{%")
    lines.append(r"\begin{tabular}{llrrrrrr}")
    lines.append(r"\toprule")
    lines.append(r"Corpus & Level & Requested (B) & Emitted (B) & klauspost ratio & "
                 r"Default ratio & Full (ours) ratio & $\Delta$ klauspost vs.\ Default \\")
    lines.append(r"\midrule")
    for r in sorted(e2_rows, key=lambda r: (r["corpus"], r["level"], variant_requested_size(r["variant"]) or 0)):
        corpus, level = r["corpus"], r["level"]
        requested = variant_requested_size(r["variant"])
        emitted = r["dict_size"]
        default = main_by_cl.get((corpus, level), {}).get("default")
        full = main_by_cl.get((corpus, level), {}).get("full")
        d = delta_pct(r["ratio"], default)
        undersized = requested is not None and requested > 0 and emitted < UNDERSIZED_FRAC * requested
        if undersized:
            any_undersized = True
        emitted_str = fmt_bytes(emitted) + (r"$^\dagger$" if undersized else "")
        lines.append(
            f"{esc(corpus)} & {level} & {fmt_bytes(requested)} & {emitted_str} & "
            f"{fmt_ratio(r['ratio'])} & {fmt_ratio(default)} & {fmt_ratio(full)} & "
            f"{fmt_delta_pct(d)} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}%")
    lines.append(r"}")
    if any_undersized:
        lines.append(r"\vspace{2pt}")
        lines.append(r"\par\noindent\footnotesize $\dagger$ klauspost/compress's "
                     r"\texttt{builddict} emitted a dictionary far smaller than the requested "
                     r"budget in these rows (undersized-emission behaviour); ratios are still "
                     r"computed at the emitted size, not the requested one.")
    lines.append(r"\end{table}")
    write_lines(out_dir / "t3_baselines.tex", lines)


# ---------------------------------------------------------------------
# t4_parity.tex
# ---------------------------------------------------------------------

def build_t4_parity(parity_csv, out_dir):
    if not parity_csv.exists():
        warn(f"{parity_csv} not found (parity campaign may still be running); "
             f"t4_parity.tex will be a \\todo placeholder")
        write_placeholder(
            out_dir / "t4_parity.tex",
            "t4: results/parity_v2.csv not found -- the matched-size / "
            "production-config parity campaign (tools/run_parity.py) has not "
            "produced output yet. Re-run tools/make_tables.py once it has.",
            "t4_parity",
        )
        return

    rows = load_rows(parity_csv)
    if not rows:
        warn(f"{parity_csv} present but empty/unparseable; t4_parity.tex will be a placeholder")
        write_placeholder(
            out_dir / "t4_parity.tex",
            "t4: results/parity_v2.csv is present but contains no usable rows.",
            "t4_parity",
        )
        return

    # Schema assumed identical to benchmark_v2.csv (experiment, corpus,
    # level, variant, dict_size, ratio, train_wall_s, note). Degrade to
    # whatever subset of expected columns/rows is actually present --
    # load_rows() already skips malformed rows individually.
    lines = []
    lines.append(header_comment("t4_parity: matched-size / production-config comparisons"))
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\caption{Matched-size and production-configuration parity comparisons "
                 r"(e.g.\ Cassandra CEP-54's 64KB default, ScyllaDB's L1 RPC dictionary, "
                 r"RocksDB's finalize-raw fallback), from the parity campaign "
                 r"(\texttt{tools/run\_parity.py}).}")
    lines.append(r"\label{tab:t4-parity}")
    lines.append(r"\resizebox{\linewidth}{!}{%")
    lines.append(r"\begin{tabular}{llllrl}")
    lines.append(r"\toprule")
    lines.append(r"Corpus & Level & Variant & Dict.\ size (B) & Ratio & Note \\")
    lines.append(r"\midrule")
    for r in sorted(rows, key=lambda r: (r["corpus"], r["level"], r["variant"])):
        lines.append(
            f"{esc(r['corpus'])} & {r['level']} & {esc(r['variant'])} & "
            f"{fmt_bytes(r['dict_size'])} & {fmt_ratio(r['ratio'])} & {esc(r['note'])[:60]} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}%")
    lines.append(r"}")
    lines.append(r"\end{table}")
    write_lines(out_dir / "t4_parity.tex", lines)


# ---------------------------------------------------------------------
# output helpers
# ---------------------------------------------------------------------

def write_lines(path, lines):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    try:
        shown = path.relative_to(REPO_ROOT)
    except ValueError:
        shown = path
    info(f"wrote {shown}")


def write_placeholder(path, todo_text, table_name):
    lines = [
        header_comment(f"{table_name}: placeholder, no data available"),
        r"% This table could not be generated -- see the \todo note below.",
        rf"\todo{{{todo_text}}}",
    ]
    write_lines(path, lines)


# ---------------------------------------------------------------------
# main
# ---------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    ap.add_argument("--parity-csv", type=Path, default=DEFAULT_PARITY_CSV)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = ap.parse_args()

    rows = load_rows(args.csv)
    if not rows:
        warn(f"no usable rows in {args.csv}; all main-CSV tables will be placeholders")

    args.out_dir.mkdir(parents=True, exist_ok=True)

    build_t1_main(rows, args.out_dir)
    build_t2_equalcompute(rows, args.out_dir)
    build_t3_baselines(rows, args.out_dir)
    build_t4_parity(args.parity_csv, args.out_dir)


if __name__ == "__main__":
    main()
